# -*- coding: utf-8 -*-
"""PI-Deeponet reaction diffusion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/pi-deeponet-reaction-diffusion-77fe71ea-b6c1-47df-a175-8abcecd3cd6e.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20240910/auto/storage/goog4_request%26X-Goog-Date%3D20240910T123109Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D89a3d010d751cf3e607a9cab3ce09a0480409c3a070fa5a764f4d77aabb6c22b7d8fa8d8f9c7b1d78683fa012a7628218224badacbf0e79668accbd4d87e4a9f43acfc3e6e2e3be948f23bd26537733ea642ce65dce2277c0b281c63c4e9a3814ab7e805a82f1109b334f09af6a6e159ce99231eedf8095389023cf27dba218008624b1ee5f0a5cc19bc82923ada41ff881aae9064f017eddc97e07899900d4d1c4125e28e76466261879ed1a070f75cc0b3e51d5ebba90c472cf580929c68e49a7483f590dd2135538d06e68542599560f0208ae7b9aad4cb4b9554646d71c1d39cd99851780da57333495bd521fadb068c3b3fb4abda08375c685dfc72c59f
"""



"""# PI-Deeponet+Data

$$\frac{\partial s}{\partial t} = D_{coeff}\frac{\partial^2 s}{\partial x^2} + K_{coeff}s^2 + u(x)$$\
$$s(x,0) = 0$$


boundary condition: periodic\
$domain$ : $$x = [0,1],t = [0,1]$$
"""

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Input, Dense, concatenate, Lambda
from tensorflow.keras.utils import to_categorical
import scipy.io
import time as time_lib
import scipy.optimize
from scipy.fft import fft, ifft
from scipy.integrate import odeint
import time
import math

"""##Training Data preparation"""

n_functions=50 #no of functions
n_sensors=20 #no of sensor points

lb_A=-1 #lowerbound of coefficient
ub_A=1 #upperbound of coefficient
L=1
nx = 50 # no of grid points for x
nt = 50 # no of grid points for t

n_bdr=400
n_train=nx*nt

# domain
x_0=0
x_l=1
t_0=0
t_l=1

#for trunck-inside points
x=np.linspace(x_0,x_l,nx)
t=np.linspace(t_0,t_l,nt)

#boundary points 1 (t=0)
x_bdr=np.random.rand(n_bdr)
t_bdr=np.zeros(n_bdr)

#boundary points 2 (x=0 and x=L)
x_bdr2=np.zeros(n_bdr)
t_bdr2=np.random.rand(n_bdr)

#for trunck
x_sensor=np.linspace(0,1,n_sensors)

t=np.reshape(t,(len(t),1))
x=np.reshape(x,(len(x),1))

x_eval,t_eval = np.meshgrid(x,t)
x_eval=np.reshape(x_eval,-1)
t_eval=np.reshape(t_eval,-1)

x_bdr=np.reshape(x_bdr,-1)
t_bdr=np.reshape(t_bdr,-1)

x_bdr2=np.reshape(x_bdr2,-1)
t_bdr2=np.reshape(t_bdr2,-1)

y=np.concatenate([x_eval[:, None], t_eval[:, None]],axis=1)
y_bdr=np.concatenate([x_bdr[:, None], t_bdr[:, None]],axis=1)
y_bdr2=np.concatenate([x_bdr2[:, None], t_bdr2[:, None]],axis=1)

A=np.random.rand(n_functions)
B=np.random.rand(n_functions)

D_coeff  = 0.01 # constant in PDE
K_coeff = 0.01 # constant in PDE

#functions
def fn(A,B,x):
    return B*np.cos(A*x)+A*np.sin(B*x)+A*np.e**(-A*x)-B*np.e**(B*x)+np.log(1+A)+B*A*np.log(1+A*B)#+(A*B*x**2+x+B+A*B**2)**2+A*x+B*x**2

#DNS
def sol_reaction_diff(u,t,K_coeff,D_coeff):

    s_0 = u*0.0

    def rhsf(s, t):
        N = len(s)
        n = np.arange(N); n[int(N/2)+1:]-= N
        return K_coeff*s**2 - D_coeff*ifft((2*np.pi*n/L)**2*fft(s)).real + u
    sol = odeint(rhsf, s_0, t)

    return sol

f=[]
for i in range(n_functions):
    f.append(fn(A[i],B[i],x_sensor))

f=np.array(f)

f.shape

#create X_train

#x_branch and x_branch to train
X_train_branch=[]
X_train_trunck=[]
A_train=[]
B_train=[]
x = np.linspace(0, 1, nx)
t = np.linspace(0, 1, nt)
y_true=[]

for i in range(n_functions):
    u_inp_fun = fn(A[i], B[i], x)
    sol_fun = sol_reaction_diff(u_inp_fun, t, K_coeff, D_coeff)
    sol_fun =np.reshape(sol_fun,-1)
    for j in range(n_train):
        X_train_branch.append(f[i])
        X_train_trunck.append(y[j])
        A_train.append(A[i])
        B_train.append(B[i])
        y_true.append(sol_fun[j])

X_train_branch=np.array(X_train_branch)
X_train_trunck=np.array(X_train_trunck)

A_train=np.array(A_train)
B_train=np.array(B_train)
y_true=np.array(y_true)

#create X_train for boundary (t=0)

#x_branch and x_branch to train
X_train_branch_bdr=[]
X_train_trunck_bdr=[]
A_train_bdr=[]
B_train_bdr=[]

for i in range(n_functions):
    for j in range(n_bdr):
        X_train_branch_bdr.append(f[i])
        X_train_trunck_bdr.append(y_bdr[j])

        A_train_bdr.append(A[i])
        B_train_bdr.append(B[i])

X_train_branch_bdr=np.array(X_train_branch_bdr)
X_train_trunck_bdr=np.array(X_train_trunck_bdr)

A_train_bdr=np.array(A_train_bdr)
B_train_bdr=np.array(B_train_bdr)

#create X_train for boundary(x=0 )

#x_branch and x_branch to train
X_train_branch_bdr2=[]
X_train_trunck_bdr2=[]
A_train_bdr2=[]
B_train_bdr2=[]

for i in range(n_functions):
    for j in range(n_bdr):
        X_train_branch_bdr2.append(f[i])
        X_train_trunck_bdr2.append(y_bdr2[j])

        A_train_bdr2.append(A[i])
        B_train_bdr2.append(B[i])

X_train_branch_bdr2=np.array(X_train_branch_bdr2)
X_train_trunck_bdr2=np.array(X_train_trunck_bdr2)

A_train_bdr2=np.array(A_train_bdr2)
B_train_bdr2=np.array(B_train_bdr2)

X_train_br=tf.convert_to_tensor(X_train_branch, dtype=tf.float32, dtype_hint=None, name=None)
X_train_tr=tf.convert_to_tensor(X_train_trunck, dtype=tf.float32, dtype_hint=None, name=None)
A_train=tf.convert_to_tensor(A_train, dtype=tf.float32, dtype_hint=None, name=None)
B_train=tf.convert_to_tensor(B_train, dtype=tf.float32, dtype_hint=None, name=None)
y_true=tf.convert_to_tensor(y_true, dtype=tf.float32, dtype_hint=None, name=None)

X_train_br_bdr=tf.convert_to_tensor(X_train_branch_bdr, dtype=tf.float32, dtype_hint=None, name=None)
X_train_tr_bdr=tf.convert_to_tensor(X_train_trunck_bdr, dtype=tf.float32, dtype_hint=None, name=None)
A_train_bdr=tf.convert_to_tensor(A_train_bdr, dtype=tf.float32, dtype_hint=None, name=None)
B_train_bdr=tf.convert_to_tensor(B_train_bdr, dtype=tf.float32, dtype_hint=None, name=None)

X_train_br_bdr2=tf.convert_to_tensor(X_train_branch_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
X_train_tr_bdr2=tf.convert_to_tensor(X_train_trunck_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
A_train_bdr2=tf.convert_to_tensor(A_train_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
B_train_bdr2=tf.convert_to_tensor(B_train_bdr2, dtype=tf.float32, dtype_hint=None, name=None)

dataset = tf.data.Dataset.from_tensor_slices((X_train_br, X_train_tr, A_train,B_train,y_true))
dataset_bdr=tf.data.Dataset.from_tensor_slices((X_train_br_bdr, X_train_tr_bdr, A_train_bdr,B_train_bdr))
dataset_bdr2=tf.data.Dataset.from_tensor_slices((X_train_br_bdr2, X_train_tr_bdr2, A_train_bdr2,B_train_bdr2))

batch_size = 25000  # Adjust this based on needs
batch_size_bdr = 4000
batch_size_bdr2 = 4000

dataset = dataset.batch(batch_size)
dataset_bdr = dataset_bdr.batch(batch_size_bdr)
dataset_bdr2 = dataset_bdr2.batch(batch_size_bdr2)

"""## DeepOnet mdoel Architecture and PINN Loss"""

# Define the optimizer
optimizer = tf.keras.optimizers.Adam()
tf.keras.backend.set_floatx('float32')

################### ~model for deepOnet~ #########################################################

#no of sensor points
m=n_sensors
branch_input = Input(shape=(m,), name='vector_input')
trunck_input = Input(shape=(2,), name='scalar_input')

#branch network
branch_net = Dense(128, activation='tanh')(branch_input)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(m, activation='tanh')(branch_net)

# Trunck network
trunck_net = Dense(128, activation='tanh')(trunck_input)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(m, activation='tanh')(trunck_net)
#bias = tf.Variable(0., shape=(), trainable=True)

dot_product = Lambda(lambda x: tf.reduce_sum(x[0] * x[1], axis=1, keepdims=True))([branch_net, trunck_net])
model = tf.keras.Model(inputs=[branch_input, trunck_input], outputs=dot_product)

############################# Loss Functions ##################################################

def PINN_loss(X_br,X_tr,A,B):
    with tf.GradientTape(persistent=True) as tape:

            x,t=tf.unstack(X_tr,axis=1)
            tape.watch(x)
            tape.watch(t)

            s = model([X_br, tf.stack((x,t),axis=1)], training=True)
            dsdx=tape.gradient(s,x)
            d2sdx2=tape.gradient(dsdx,x)

            dsdt=tape.gradient(s,t)
            u=fn(A,B,x)

            loss = tf.reduce_mean(tf.square(dsdt-D_coeff*d2sdx2-K_coeff*tf.square(s)-u))
    del tape
    return loss

def data_loss(X_br,X_tr,y_tr):
    with tf.GradientTape(persistent=True) as tape:

            #x,t=tf.unstack(X_tr,axis=1)
            #tape.watch(x)
            #tape.watch(t)
            s = model([X_br, X_tr], training=True)
            loss = tf.reduce_mean(tf.square(s-y_tr))
    del tape
    return loss

def loss_bdr(X_br,X_tr,A,B):
    with tf.GradientTape(persistent=True) as tape:

            x,t=tf.unstack(X_tr,axis=1)
            tape.watch(x)
            tape.watch(t)

            s = model([X_br, tf.stack((x,t),axis=1)], training=True)
            dsdx=tape.gradient(s,x)
            d2sdx2=tape.gradient(dsdx,x)

            dsdt=tape.gradient(s,t)
            u=fn(A,B,x)

            loss2=tf.reduce_mean(tf.square(s))#initial loss
            loss = tf.reduce_mean(tf.square(dsdt-D_coeff*d2sdx2-K_coeff*tf.square(s)-u))#equation loss
    del tape
    return (loss+loss2)/2

def loss_bdr2(X_br,X_tr,A,B):
    with tf.GradientTape(persistent=True) as tape:

            x,t=tf.unstack(X_tr,axis=1)
            xl=x+L
            tape.watch(x)
            tape.watch(t)
            tape.watch(xl)

            s = model([X_br, tf.stack((x,t),axis=1)], training=True)
            s1 = model([X_br, tf.stack((xl,t),axis=1)], training=True)

            dsdx=tape.gradient(s,x)
            d2sdx2=tape.gradient(dsdx,x)

            ds1dx=tape.gradient(s1,xl)
            d2s1dx2=tape.gradient(ds1dx,xl)

            dsdt=tape.gradient(s,t)
            ds1dt=tape.gradient(s1,t)

            u=fn(A,B,x)

            loss_bdr=tf.reduce_mean(tf.square(s-s1))
            loss_bdr_2=tf.reduce_mean(tf.square(dsdx-ds1dx))

            loss1 = tf.reduce_mean(tf.square(dsdt-D_coeff*d2sdx2-K_coeff*tf.square(s)-u))#equation loss at x=0
            loss2 = tf.reduce_mean(tf.square(ds1dt-D_coeff*d2s1dx2-K_coeff*tf.square(s1)-u))#equation loss at x=L

    del tape
    return (loss_bdr+loss_bdr_2)/4

#Ration of no of PINN loss points to data loss"
equations_to_data_ratio=20/1

# Define a learning rate schedule
initial_learning_rate = 1e-3
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate, decay_steps=100, decay_rate=0.9)

# Define the optimizer with the learning rate schedule
optimizer = tf.keras.optimizers.Adam(learning_rate=lr_schedule)

loss_total=[]
epochs=[]
time1=[]

######################### TRAINING LOOP ######################################
start1=time.time()
for epoch in range(1500):

    #randomly shuffling the dataset
    #dataset = dataset.shuffle(buffer_size=len(X_train_br))
    '.............................................................................'
    # PINN
    for X_br, X_tr, A,B,y_true in dataset:
        with tf.GradientTape() as tape:
            loss_value = PINN_loss(X_br,X_tr,A,B)
        grads = tape.gradient(loss_value, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))
        del tape
    '.............................................................................'
    # Data
#     loss_value_data=0

#     if(epoch%(equations_to_data_ratio)==0):
#         for X_br, X_tr, A,B,y_true in dataset:
#             with tf.GradientTape() as tape:

#                 loss_value_data = data_loss(X_br,X_tr,y_true)
#             grads = tape.gradient(loss_value_data, model.trainable_variables)
#             optimizer.apply_gradients(zip(grads, model.trainable_variables))

    '.............................................................................'
    # Initial
    for X_br, X_tr, A,B in dataset_bdr:
        with tf.GradientTape() as tape:

            loss_value_bdr = loss_bdr(X_br,X_tr,A,B)
        grads = tape.gradient(loss_value_bdr, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))
        del tape
    '.............................................................................'
   # Boundary
    '''
    for X_br, X_tr, A,B in dataset_bdr2:
        with tf.GradientTape() as tape:
            loss_value_bdr2 = loss_bdr2(X_br,X_tr,A,B)
        grads = tape.gradient(loss_value_bdr2, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))

    '''
    '.............................................................................'

    loss_total_f=loss_value+loss_value_bdr#+loss_value_data#+loss_value_bdr2
    loss_total.append(loss_total_f)
    epochs.append(epoch)

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, loss={loss_total_f:.6f}")
    #print(f"Epoch {epoch}, loss={loss_value:.6f}", end='\r')
    t=time.time()
    time1.append(t)
    ################################################################################

end1=time.time()
print((end1-start1)/100)

total_params = model.count_params()

print(total_params)

#prediction for a-new function, test new data preparation
A_new=np.random.rand()
B_new=np.random.rand()
X_test_branch=[]
X_test_trunck=[]

f_new=fn(A_new,B_new,x_sensor)
for i in range(1):
    for j in range(n_train):
        X_test_branch.append(f_new)
        X_test_trunck.append(y[j])

#testing data
X_test_branch=np.array(X_test_branch)
X_test_trunck=np.array(X_test_trunck)

#new unseen function pred
s=model([X_test_branch,X_test_trunck])
pred=tf.reshape(s,(nx,nt))

fig, axes = plt.subplots(1, 2, figsize=(16, 4))

# First set of plots
ax1 = axes[0]
ax1.set_title('PI-DeepOnet Prediction')
im1 = ax1.imshow(pred, cmap='jet', origin='lower')
fig.colorbar(im1, orientation='vertical')

# Second set of plots
ax2 = axes[1]
ax2.set_title('Numerical solution')
x = np.linspace(0, 1, nx)
t = np.linspace(0, 1, nt)
u_inp_fun = fn(A_new, B_new, x)
sol_fun = sol_reaction_diff(u_inp_fun, t, K_coeff, D_coeff)
im2 = ax2.imshow(sol_fun, cmap='jet', origin='lower')
fig.colorbar(im2, orientation='vertical')

plt.show()

"""# SPI Deeponet"""

# Define the optimizer
optimizer = tf.keras.optimizers.Adam()
tf.keras.backend.set_floatx('float32')

# Branch Network (remains unchanged)
m = n_sensors
branch_input = Input(shape=(m,), name='vector_input')
branch_net = Dense(128, activation='tanh')(branch_input)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_output = Dense(m, activation='tanh')(branch_net)

# Trunk Network for 'x' (spatial input)
trunk_x_input = Input(shape=(1,), name='x_input')  # Input for 'x'
trunk_x_net = Dense(128, activation='tanh')(trunk_x_input)
trunk_x_net = Dense(128, activation='tanh')(trunk_x_net)
trunk_x_net = Dense(128, activation='tanh')(trunk_x_net)
trunk_x_net = Dense(128, activation='tanh')(trunk_x_net)
trunk_x_net = Dense(128, activation='tanh')(trunk_x_net)
trunk_x_net = Dense(128, activation='tanh')(trunk_x_net)
trunk_x_output = Dense(m, activation='tanh')(trunk_x_net)  # Output should match the size of the branch network output

# Trunk Network for 't' (temporal input)
trunk_t_input = Input(shape=(1,), name='t_input')  # Input for 't'
trunk_t_net = Dense(128, activation='tanh')(trunk_t_input)
trunk_t_net = Dense(128, activation='tanh')(trunk_t_net)
trunk_t_net = Dense(128, activation='tanh')(trunk_t_net)
trunk_t_net = Dense(128, activation='tanh')(trunk_t_net)
trunk_t_net = Dense(128, activation='tanh')(trunk_t_net)
trunk_t_net = Dense(128, activation='tanh')(trunk_t_net)
trunk_t_output = Dense(m, activation='tanh')(trunk_t_net)  # Output should match the size of the branch network output

# Element-wise multiplication of branch and trunk outputs
spinn_output =Lambda(lambda x: tf.reduce_sum(x[0] * x[1] * x[2], axis=1, keepdims=True))([branch_output, trunk_x_output,trunk_t_output])

# Define the SPINN model
model = tf.keras.Model(inputs=[branch_input, trunk_x_input,trunk_t_input], outputs=spinn_output)

############################# Loss Functions ##################################################
def loss(X_br, X_tr, A, B):
    with tf.GradientTape(persistent=True) as tape:
        x, t = tf.unstack(X_tr, axis=1)
        tape.watch(x)
        tape.watch(t)

        s = model([X_br, x,t], training=True)
        dsdx = tape.gradient(s, x)
        d2sdx2 = tape.gradient(dsdx, x)

        dsdt = tape.gradient(s, t)
        u = fn(A, B, x)

        loss = tf.reduce_mean(tf.square(dsdt - D_coeff * d2sdx2 - K_coeff * tf.square(s) - u))
    del tape
    return loss

def loss_bdr(X_br, X_tr, A, B):
    with tf.GradientTape(persistent=True) as tape:
        x, t = tf.unstack(X_tr, axis=1)
        tape.watch(x)
        tape.watch(t)

        s = model([X_br, x,t], training=True)
        dsdx = tape.gradient(s, x)
        d2sdx2 = tape.gradient(dsdx, x)

        dsdt = tape.gradient(s, t)
        u = fn(A, B, x)

        loss2 = tf.reduce_mean(tf.square(s))  # Initial condition loss
        loss = tf.reduce_mean(tf.square(dsdt - D_coeff * d2sdx2 - K_coeff * tf.square(s) - u))  # PDE loss
    del tape
    return (loss + loss2) / 2

def loss_bdr2(X_br, X_tr, A, B):
    with tf.GradientTape(persistent=True) as tape:
        x, t = tf.unstack(X_tr, axis=1)
        xl = x + L
        tape.watch(x)
        tape.watch(t)
        tape.watch(xl)

        s = model([X_br,x,t], training=True)
        s1 = model([X_br,xl,t], training=True)

        dsdx = tape.gradient(s, x)
        d2sdx2 = tape.gradient(dsdx, x)

        ds1dx = tape.gradient(s1, xl)
        d2s1dx2 = tape.gradient(ds1dx, xl)

        dsdt = tape.gradient(s, t)
        ds1dt = tape.gradient(s1, t)

        u = fn(A, B, x)

        loss_bdr = tf.reduce_mean(tf.square(s - s1))
        loss_bdr_2 = tf.reduce_mean(tf.square(dsdx - ds1dx))

        loss1 = tf.reduce_mean(tf.square(dsdt - D_coeff * d2sdx2 - K_coeff * tf.square(s) - u))  # Equation loss at x=0
        loss2 = tf.reduce_mean(tf.square(ds1dt - D_coeff * d2s1dx2 - K_coeff * tf.square(s1) - u))  # Equation loss at x=L
    del tape
    return (loss_bdr + loss_bdr_2) / 4

"""##Training LOOP"""

#Ration of no of PINN loss points to data loss"
equations_to_data_ratio=20/1

# Define a learning rate schedule
initial_learning_rate = 1e-3
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate, decay_steps=100, decay_rate=0.9)

# Define the optimizer with the learning rate schedule
optimizer = tf.keras.optimizers.Adam(learning_rate=lr_schedule)

loss_total2=[]
epochs=[]
time2=[]
start2=time.time()
######################### TRAINING LOOP ######################################
for epoch in range(1500):

    #randomly shuffling the dataset
    #dataset = dataset.shuffle(buffer_size=len(X_train_br))
    '.............................................................................'
    # PINN
    for X_br, X_tr, A,B,y_true in dataset:
        with tf.GradientTape() as tape:
            loss_value = loss(X_br,X_tr,A,B)
        grads = tape.gradient(loss_value, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))
        del tape
    '.............................................................................'
    # Data
#     loss_value_data=0

#     if(epoch%(equations_to_data_ratio)==0):
#         for X_br, X_tr, A,B,y_true in dataset:
#             with tf.GradientTape() as tape:

#                 loss_value_data = data_loss(X_br,X_tr,y_true)
#             grads = tape.gradient(loss_value_data, model.trainable_variables)
#             optimizer.apply_gradients(zip(grads, model.trainable_variables))

    '.............................................................................'
    # Initial
    for X_br, X_tr, A,B in dataset_bdr:
        with tf.GradientTape() as tape:

            loss_value_bdr = loss_bdr(X_br,X_tr,A,B)
        grads = tape.gradient(loss_value_bdr, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))
        del tape
    '.............................................................................'
   # Boundary
    '''
    for X_br, X_tr, A,B in dataset_bdr2:
        with tf.GradientTape() as tape:
            loss_value_bdr2 = loss_bdr2(X_br,X_tr,A,B)
        grads = tape.gradient(loss_value_bdr2, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))

    '''
    '.............................................................................'

    loss_total_f=loss_value+loss_value_bdr#+loss_value_data#+loss_value_bdr2
    loss_total2.append(loss_total_f)
    epochs.append(epoch)

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, loss={loss_total_f:.6f}")
    #print(f"Epoch {epoch}, loss={loss_value:.6f}", end='\r')
    t=time.time();
    time2.append(t)
    ################################################################################

end2=time.time()
print((end2-start2)/100)

total_params2 = model.count_params()
print(total_params2)

t1=end1-start1
t2=end2-start2
ttt=[t1,t2]
par=[total_params,total_params2]
tim_per=[t1/total_params,t2/total_params2]

print(tim_per)
print(tim_per[0]/tim_per[1])

"""# Chebyshev"""

import numpy as np
from scipy.fft import fft, ifft
from scipy.integrate import odeint

# Given Parameters
n_functions = 50
n_sensors = 20

lb_A = -1
ub_A = 1
L = 1
nx = 50
nt = 50

n_bdr = 400
n_train = nx * nt

x_0 = 0
x_l = 1
t_0 = 0
t_l = 1

# Regular grid for x and t
x = np.linspace(x_0, x_l, nx)
t = np.linspace(t_0, t_l, nt)

# Boundary points 1 (t=0)
x_bdr = np.random.rand(n_bdr)
t_bdr = np.zeros(n_bdr)

# Boundary points 2 (x=0 and x=L)
x_bdr2 = np.zeros(n_bdr)
t_bdr2 = np.random.rand(n_bdr)

# Chebyshev Grid for sensor points (x_sensor)
i_sensor = np.arange(n_sensors)
x_sensor_chebyshev = np.cos((2 * i_sensor + 1) * np.pi / (2 * n_sensors))

# Rescale to the interval [0, 1]
x_sensor = (x_sensor_chebyshev + 1) * 0.5

# Reshape t and x for meshgrid
t = np.reshape(t, (len(t), 1))
x = np.reshape(x, (len(x), 1))

# Meshgrid and evaluation points
x_eval, t_eval = np.meshgrid(x, t)
x_eval = np.reshape(x_eval, -1)
t_eval = np.reshape(t_eval, -1)

# Boundary reshaping
x_bdr = np.reshape(x_bdr, -1)
t_bdr = np.reshape(t_bdr, -1)
x_bdr2 = np.reshape(x_bdr2, -1)
t_bdr2 = np.reshape(t_bdr2, -1)

# Concatenate x and t for inputs
y = np.concatenate([x_eval[:, None], t_eval[:, None]], axis=1)
y_bdr = np.concatenate([x_bdr[:, None], t_bdr[:, None]], axis=1)
y_bdr2 = np.concatenate([x_bdr2[:, None], t_bdr2[:, None]], axis=1)

# Coefficients
A = np.random.rand(n_functions)
B = np.random.rand(n_functions)

D_coeff = 0.01
K_coeff = 0.01

def fn(A,B,x):
    return B*np.cos(A*x)+A*np.sin(B*x)+A*np.e**(-A*x)-B*np.e**(B*x)+np.log(1+A)+B*A*np.log(1+A*B)#+(A*B*x**2+x+B+A*B**2)**2+A*x+B*x**2

# DNS solution function
def sol_reaction_diff(u, t, K_coeff, D_coeff):
    s_0 = u * 0.0

    def rhsf(s, t):
        N = len(s)
        n = np.arange(N)
        n[int(N / 2) + 1:] -= N
        return K_coeff * s**2 - D_coeff * ifft((2 * np.pi * n / L)**2 * fft(s)).real + u

    sol = odeint(rhsf, s_0, t)
    return sol

# Evaluate functions on the Chebyshev sensor grid
f = []
for i in range(n_functions):
    f.append(fn(A[i], B[i], x_sensor))

f = np.array(f)

#create X_train

#x_branch and x_branch to train
X_train_branch=[]
X_train_trunck=[]
A_train=[]
B_train=[]
x = np.linspace(0, 1, nx)
t = np.linspace(0, 1, nt)
y_true=[]

for i in range(n_functions):
    u_inp_fun = fn(A[i], B[i], x)
    sol_fun = sol_reaction_diff(u_inp_fun, t, K_coeff, D_coeff)
    sol_fun =np.reshape(sol_fun,-1)
    for j in range(n_train):
        X_train_branch.append(f[i])
        X_train_trunck.append(y[j])
        A_train.append(A[i])
        B_train.append(B[i])
        y_true.append(sol_fun[j])

X_train_branch=np.array(X_train_branch)
X_train_trunck=np.array(X_train_trunck)

A_train=np.array(A_train)
B_train=np.array(B_train)
y_true=np.array(y_true)

#create X_train for boundary (t=0)

#x_branch and x_branch to train
X_train_branch_bdr=[]
X_train_trunck_bdr=[]
A_train_bdr=[]
B_train_bdr=[]

for i in range(n_functions):
    for j in range(n_bdr):
        X_train_branch_bdr.append(f[i])
        X_train_trunck_bdr.append(y_bdr[j])

        A_train_bdr.append(A[i])
        B_train_bdr.append(B[i])

X_train_branch_bdr=np.array(X_train_branch_bdr)
X_train_trunck_bdr=np.array(X_train_trunck_bdr)

A_train_bdr=np.array(A_train_bdr)
B_train_bdr=np.array(B_train_bdr)

#create X_train for boundary(x=0 )

#x_branch and x_branch to train
X_train_branch_bdr2=[]
X_train_trunck_bdr2=[]
A_train_bdr2=[]
B_train_bdr2=[]

for i in range(n_functions):
    for j in range(n_bdr):
        X_train_branch_bdr2.append(f[i])
        X_train_trunck_bdr2.append(y_bdr2[j])

        A_train_bdr2.append(A[i])
        B_train_bdr2.append(B[i])

X_train_branch_bdr2=np.array(X_train_branch_bdr2)
X_train_trunck_bdr2=np.array(X_train_trunck_bdr2)

A_train_bdr2=np.array(A_train_bdr2)
B_train_bdr2=np.array(B_train_bdr2)

X_train_br=tf.convert_to_tensor(X_train_branch, dtype=tf.float32, dtype_hint=None, name=None)
X_train_tr=tf.convert_to_tensor(X_train_trunck, dtype=tf.float32, dtype_hint=None, name=None)
A_train=tf.convert_to_tensor(A_train, dtype=tf.float32, dtype_hint=None, name=None)
B_train=tf.convert_to_tensor(B_train, dtype=tf.float32, dtype_hint=None, name=None)
y_true=tf.convert_to_tensor(y_true, dtype=tf.float32, dtype_hint=None, name=None)

X_train_br_bdr=tf.convert_to_tensor(X_train_branch_bdr, dtype=tf.float32, dtype_hint=None, name=None)
X_train_tr_bdr=tf.convert_to_tensor(X_train_trunck_bdr, dtype=tf.float32, dtype_hint=None, name=None)
A_train_bdr=tf.convert_to_tensor(A_train_bdr, dtype=tf.float32, dtype_hint=None, name=None)
B_train_bdr=tf.convert_to_tensor(B_train_bdr, dtype=tf.float32, dtype_hint=None, name=None)

X_train_br_bdr2=tf.convert_to_tensor(X_train_branch_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
X_train_tr_bdr2=tf.convert_to_tensor(X_train_trunck_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
A_train_bdr2=tf.convert_to_tensor(A_train_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
B_train_bdr2=tf.convert_to_tensor(B_train_bdr2, dtype=tf.float32, dtype_hint=None, name=None)

dataset = tf.data.Dataset.from_tensor_slices((X_train_br, X_train_tr, A_train,B_train,y_true))
dataset_bdr=tf.data.Dataset.from_tensor_slices((X_train_br_bdr, X_train_tr_bdr, A_train_bdr,B_train_bdr))
dataset_bdr2=tf.data.Dataset.from_tensor_slices((X_train_br_bdr2, X_train_tr_bdr2, A_train_bdr2,B_train_bdr2))

batch_size = 25000  # Adjust this based on needs
batch_size_bdr = 4000
batch_size_bdr2 = 4000

dataset = dataset.batch(batch_size)
dataset_bdr = dataset_bdr.batch(batch_size_bdr)
dataset_bdr2 = dataset_bdr2.batch(batch_size_bdr2)

# Define the optimizer
optimizer = tf.keras.optimizers.Adam()
tf.keras.backend.set_floatx('float32')

################### ~model for deepOnet~ #########################################################

#no of sensor points
m=n_sensors
branch_input = Input(shape=(m,), name='vector_input')
trunck_input = Input(shape=(2,), name='scalar_input')

#branch network
branch_net = Dense(128, activation='tanh')(branch_input)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(m, activation='tanh')(branch_net)

# Trunck network
trunck_net = Dense(128, activation='tanh')(trunck_input)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(m, activation='tanh')(trunck_net)
#bias = tf.Variable(0., shape=(), trainable=True)

dot_product = Lambda(lambda x: tf.reduce_sum(x[0] * x[1], axis=1, keepdims=True))([branch_net, trunck_net])
model = tf.keras.Model(inputs=[branch_input, trunck_input], outputs=dot_product)

############################# Loss Functions ##################################################

def PINN_loss(X_br,X_tr,A,B):
    with tf.GradientTape(persistent=True) as tape:

            x,t=tf.unstack(X_tr,axis=1)
            tape.watch(x)
            tape.watch(t)

            s = model([X_br, tf.stack((x,t),axis=1)], training=True)
            dsdx=tape.gradient(s,x)
            d2sdx2=tape.gradient(dsdx,x)

            dsdt=tape.gradient(s,t)
            u=fn(A,B,x)

            loss = tf.reduce_mean(tf.square(dsdt-D_coeff*d2sdx2-K_coeff*tf.square(s)-u))
    del tape
    return loss

def data_loss(X_br,X_tr,y_tr):
    with tf.GradientTape(persistent=True) as tape:

            #x,t=tf.unstack(X_tr,axis=1)
            #tape.watch(x)
            #tape.watch(t)
            s = model([X_br, X_tr], training=True)
            loss = tf.reduce_mean(tf.square(s-y_tr))
    del tape
    return loss

def loss_bdr(X_br,X_tr,A,B):
    with tf.GradientTape(persistent=True) as tape:

            x,t=tf.unstack(X_tr,axis=1)
            tape.watch(x)
            tape.watch(t)

            s = model([X_br, tf.stack((x,t),axis=1)], training=True)
            dsdx=tape.gradient(s,x)
            d2sdx2=tape.gradient(dsdx,x)

            dsdt=tape.gradient(s,t)
            u=fn(A,B,x)

            loss2=tf.reduce_mean(tf.square(s))#initial loss
            loss = tf.reduce_mean(tf.square(dsdt-D_coeff*d2sdx2-K_coeff*tf.square(s)-u))#equation loss
    del tape
    return (loss+loss2)/2

def loss_bdr2(X_br,X_tr,A,B):
    with tf.GradientTape(persistent=True) as tape:

            x,t=tf.unstack(X_tr,axis=1)
            xl=x+L
            tape.watch(x)
            tape.watch(t)
            tape.watch(xl)

            s = model([X_br, tf.stack((x,t),axis=1)], training=True)
            s1 = model([X_br, tf.stack((xl,t),axis=1)], training=True)

            dsdx=tape.gradient(s,x)
            d2sdx2=tape.gradient(dsdx,x)

            ds1dx=tape.gradient(s1,xl)
            d2s1dx2=tape.gradient(ds1dx,xl)

            dsdt=tape.gradient(s,t)
            ds1dt=tape.gradient(s1,t)

            u=fn(A,B,x)

            loss_bdr=tf.reduce_mean(tf.square(s-s1))
            loss_bdr_2=tf.reduce_mean(tf.square(dsdx-ds1dx))

            loss1 = tf.reduce_mean(tf.square(dsdt-D_coeff*d2sdx2-K_coeff*tf.square(s)-u))#equation loss at x=0
            loss2 = tf.reduce_mean(tf.square(ds1dt-D_coeff*d2s1dx2-K_coeff*tf.square(s1)-u))#equation loss at x=L

    del tape
    return (loss_bdr+loss_bdr_2)/4

#Ration of no of PINN loss points to data loss"
equations_to_data_ratio=20/1

# Define a learning rate schedule
initial_learning_rate = 1e-3
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate, decay_steps=100, decay_rate=0.9)

# Define the optimizer with the learning rate schedule
optimizer = tf.keras.optimizers.Adam(learning_rate=lr_schedule)

loss_total4=[]
epochs4=[]
time4=[]

######################### TRAINING LOOP ######################################
start4=time.time()
for epoch in range(1500):

    #randomly shuffling the dataset
    #dataset = dataset.shuffle(buffer_size=len(X_train_br))
    '.............................................................................'
    # PINN
    for X_br, X_tr, A,B,y_true in dataset:
        with tf.GradientTape() as tape:
            loss_value = PINN_loss(X_br,X_tr,A,B)
        grads = tape.gradient(loss_value, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))
        del tape
    '.............................................................................'
    # Data
#     loss_value_data=0

#     if(epoch%(equations_to_data_ratio)==0):
#         for X_br, X_tr, A,B,y_true in dataset:
#             with tf.GradientTape() as tape:

#                 loss_value_data = data_loss(X_br,X_tr,y_true)
#             grads = tape.gradient(loss_value_data, model.trainable_variables)
#             optimizer.apply_gradients(zip(grads, model.trainable_variables))

    '.............................................................................'
    # Initial
    for X_br, X_tr, A,B in dataset_bdr:
        with tf.GradientTape() as tape:

            loss_value_bdr = loss_bdr(X_br,X_tr,A,B)
        grads = tape.gradient(loss_value_bdr, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))
        del tape
    '.............................................................................'
   # Boundary
    '''
    for X_br, X_tr, A,B in dataset_bdr2:
        with tf.GradientTape() as tape:
            loss_value_bdr2 = loss_bdr2(X_br,X_tr,A,B)
        grads = tape.gradient(loss_value_bdr2, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))

    '''
    '.............................................................................'

    loss_total_f=loss_value+loss_value_bdr#+loss_value_data#+loss_value_bdr2
    loss_total4.append(loss_total_f)
    epochs4.append(epoch)

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, loss={loss_total_f:.6f}")
    #print(f"Epoch {epoch}, loss={loss_value:.6f}", end='\r')
    t=time.time()
    time4.append(t)
    ################################################################################

end4=time.time()
print((end4-start4)/100)

len(loss_total2)

plt.xlabel('epochs')
plt.ylabel('Mean Squared Error')
plt.loglog(epochs4, loss_total, label='PI-Deeponet')
# plt.loglog(epochs4, loss_total2, label='SPI-Deeponet')
plt.loglog(epochs4, loss_total4, label='Chebyshev-Deeponet')
plt.legend()
plt.show()

plt.xlabel('Time')
plt.ylabel('Mean Squared Error')
plt.loglog(np.array(time1)-start1, loss_total, label='PI-Deeponet')
# plt.loglog(np.array(time2)-start2, loss_total2, label='SPI-Deeponet')
plt.loglog(np.array(time2)-start2, loss_total4, label='chebyshev deeponet')
plt.legend()
plt.show()

"""# Taylor based Deeponet"""

import math

def taylor_sin_coefficients(A, B, N):
    coefficients = []
    for n in range(N):
        if n % 2 == 0:  # Only odd powers of x have non-zero coefficients
            coefficients.append(0)
        else:
            # Calculate the coefficient for x^n
            coeff = A * ((-1)**((n-1)//2)) * (B**n) / math.factorial(n)
            coefficients.append(coeff)

    return coefficients

def taylor_cos_coefficients(A, B, N):
    coefficients = []

    for n in range(N):
        if n % 2 == 1:  # Odd powers of x have zero coefficients
            coefficients.append(0)
        else:
            # Calculate the coefficient for x^n
            coeff = A * ((-1)**(n//2)) * (B**n) / math.factorial(n)
            coefficients.append(coeff)

    return coefficients

def taylor_exp_coefficients(A, B, N):
    coefficients = []

    for n in range(N):
        # Calculate the coefficient for x^n
        coeff = A * (B**n) / math.factorial(n)
        coefficients.append(coeff)

    return coefficients

def evaluate_taylor_series(coefficients, x_values):
    series_sum = np.zeros_like(x_values)
    for n, coeff in enumerate(coefficients):
        series_sum += coeff * (x_values**n)
    return series_sum

n_functions=50 #no of functions
n_coeffs=21 #no of sensor points

lb_A=-1 #lowerbound of coefficient
ub_A=1 #upperbound of coefficient
L=1
nx = 50 # no of grid points for x
nt = 50 # no of grid points for t

n_bdr=400
n_train=nx*nt

# domain
x_0=0
x_l=1
t_0=0
t_l=1

#for trunck-inside points
x=np.linspace(x_0,x_l,nx)
t=np.linspace(t_0,t_l,nt)

#boundary points 1 (t=0)
x_bdr=np.random.rand(n_bdr)
t_bdr=np.zeros(n_bdr)

#boundary points 2 (x=0 and x=L)
x_bdr2=np.zeros(n_bdr)
t_bdr2=np.random.rand(n_bdr)

t=np.reshape(t,(len(t),1))
x=np.reshape(x,(len(x),1))

x_eval,t_eval = np.meshgrid(x,t)
x_eval=np.reshape(x_eval,-1)
t_eval=np.reshape(t_eval,-1)

x_bdr=np.reshape(x_bdr,-1)
t_bdr=np.reshape(t_bdr,-1)

x_bdr2=np.reshape(x_bdr2,-1)
t_bdr2=np.reshape(t_bdr2,-1)

y=np.concatenate([x_eval[:, None], t_eval[:, None]],axis=1)
y_bdr=np.concatenate([x_bdr[:, None], t_bdr[:, None]],axis=1)
y_bdr2=np.concatenate([x_bdr2[:, None], t_bdr2[:, None]],axis=1)

D_coeff  = 0.01 # constant in PDE
K_coeff = 0.01 # constant in PDE

#functions
# def fn(A,B,x):
#     return np.cos(2*np.pi*A*x)+np.sin(2*np.pi*B*x)+A*np.e**(-A*x)-B*np.e**(B*x)+np.log(1+A)+B*A*np.log(1+A*B)#+(A*B*x**2+x+B+A*B**2)**2+A*x+B*x**2+A+B

#DNS
def sol_reaction_diff(u,t,K_coeff,D_coeff):

    s_0 = u*0.0

    def rhsf(s, t):
        N = len(s)
        n = np.arange(N); n[int(N/2)+1:]-= N
        return K_coeff*s**2 - D_coeff*ifft((2*np.pi*n/L)**2*fft(s)).real + u
    sol = odeint(rhsf, s_0, t)

    return sol

# Arrays to store coefficients and parameters of 50 functions
f = []
params = []
A1=[]
A2=[]
B1=[]
B2=[]
C1=[]
C2=[]

for _ in range(50):
    # Random coefficients A1, A2, B1, B2, C1, C2
    a1, a2 = np.random.rand(2)
    b1, b2 = np.random.rand(2)
    c1, c2 = np.random.rand(2)*0

    # Store the parameters
    params.append([a1, a2, b1, b2, c1,c2])
    A1.append(a1)
    A2.append(a2)
    B1.append(b1)
    B2.append(b2)
    C1.append(c1)
    C2.append(c2)

    # Get coefficients for each part of the function
    cos_coeffs = taylor_cos_coefficients(a1, a2, n_coeffs)
    sin_coeffs = taylor_sin_coefficients(b1, b2, n_coeffs)
    exp_coeffs = taylor_exp_coefficients(c1, c2, n_coeffs)

    # Combine coefficients: f(x) = A1*cos(A2x) + B1*sin(B2x) + C1*exp(C2x)
    combined_coeffs = [cos_coeffs[i] + sin_coeffs[i] + exp_coeffs[i] for i in range(n_coeffs)]

    # Append to the array f
    f.append(combined_coeffs)

# Convert f and params to numpy arrays
f = np.array(f)
params = np.array(params)

# Display the shapes and the first element for verification
f.shape, params.shape


def fn(coefficients, x):
    """
    Evaluate the function value at each point in x using the provided Taylor series coefficients.

    :param coefficients: List of Taylor series coefficients
    :param x: A single value or a list of values at which to evaluate the function
    :return: A list of function values corresponding to each value in x
    """
    if isinstance(x, (int, float)):  # Check if x is a single value
        x = [x]  # Convert to list to handle uniformly

    function_values = []

    # Calculate the function value for each value in x
    for value in x:
        function_value = 0
        for n, coeff in enumerate(coefficients):
            function_value += coeff * (value ** n)
        function_values.append(function_value)

    return np.array(function_values)

def fn3(C, x):
    # Convert C to a TensorFlow tensor with shape (n, 6)
    C = tf.convert_to_tensor(C, dtype=tf.float32)

    # Convert x to a TensorFlow tensor
    x = tf.convert_to_tensor(x, dtype=tf.float32)

    # Expand dimensions of x to be compatible with C for broadcasting
    x_expanded = tf.expand_dims(x, axis=0)  # Shape (1, m) where m is the number of x values

    # Compute each term
    cos_term = C[:, 0:1] * tf.cos(C[:, 1:2] * x_expanded)
    sin_term = C[:, 2:3] * tf.sin(C[:, 3:4] * x_expanded)
    exp_term = C[:, 4:5] * tf.exp(C[:, 5:6] * x_expanded)

    # Sum the terms along the columns to get the result
    result = cos_term + sin_term + exp_term

    # Convert result to a numpy array and return
    return result.numpy()

def fn2(coefficients, x):
    """
    Evaluate the function value at x using the provided Taylor series coefficients.

    :param coefficients: List of Taylor series coefficients
    :param x: The point at which to evaluate the function
    :return: The function value at x
    """
    # Initialize the function value
    function_value = 0

    # Calculate the function value using the Taylor series
    for n, coeff in enumerate(coefficients):
        function_value += coeff * (x ** n)

    return function_value

def fun(A1,A2,B1,B2,C1,C2,x):
    return A1*np.cos(A2*x)+B1*np.sin(B2*x)+C1*np.e**(C2*x)


from typing import ParamSpec
#create X_train

#x_branch and x_branch to train
X_train_branch=[]
X_train_trunck=[]
A1_train=[]
A2_train=[]
B1_train=[]
B2_train=[]
C1_train=[]
C2_train=[]
x = np.linspace(0, 1, nx)
t = np.linspace(0, 1, nt)
y_true=[]

for i in range(n_functions):
    u_inp_fun = fun(A1[i],A2[i],B1[i],B2[i],C1[i],C2[i], x)
    sol_fun = sol_reaction_diff(u_inp_fun, t, K_coeff, D_coeff)
    sol_fun =np.reshape(sol_fun,-1)
    for j in range(n_train):
        X_train_branch.append(f[i]) #have to append coefficients here
        X_train_trunck.append(y[j])
        A1_train.append(A1[i])
        A2_train.append(A2[i])
        B1_train.append(B1[i])
        B2_train.append(B2[i])
        C1_train.append(C1[i])
        C2_train.append(C2[i])
        y_true.append(sol_fun[j])

X_train_branch=np.array(X_train_branch)
X_train_trunck=np.array(X_train_trunck)

A1_train=np.array(A1_train)
A2_train=np.array(A2_train)
B1_train=np.array(B1_train)
B2_train=np.array(B2_train)
C1_train=np.array(C1_train)
C2_train=np.array(C2_train)

y_true=np.array(y_true)

#create X_train for boundary (t=0)

#x_branch and x_branch to train
X_train_branch_bdr=[]
X_train_trunck_bdr=[]
A1_train_bdr=[]
A2_train_bdr=[]
B1_train_bdr=[]
B2_train_bdr=[]
C1_train_bdr=[]
C2_train_bdr=[]

for i in range(n_functions):
    for j in range(n_bdr):
        X_train_branch_bdr.append(f[i])
        X_train_trunck_bdr.append(y_bdr[j])

        A1_train_bdr.append(A1[i])
        A2_train_bdr.append(A2[i])
        B1_train_bdr.append(B1[i])
        B2_train_bdr.append(B2[i])
        C1_train_bdr.append(C1[i])
        C2_train_bdr.append(C2[i])

X_train_branch_bdr=np.array(X_train_branch_bdr)
X_train_trunck_bdr=np.array(X_train_trunck_bdr)

A1_train_bdr=np.array(A1_train_bdr)
A2_train_bdr=np.array(A2_train_bdr)
B1_train_bdr=np.array(B1_train_bdr)
B2_train_bdr=np.array(B2_train_bdr)
C1_train_bdr=np.array(C1_train_bdr)
C2_train_bdr=np.array(C2_train_bdr)
#create X_train for boundary(x=0 )

#x_branch and x_branch to train
X_train_branch_bdr2=[]
X_train_trunck_bdr2=[]
A1_train_bdr2=[]
A2_train_bdr2=[]
B1_train_bdr2=[]
B2_train_bdr2=[]
C1_train_bdr2=[]
C2_train_bdr2=[]

for i in range(n_functions):
    for j in range(n_bdr):
        X_train_branch_bdr2.append(f[i])
        X_train_trunck_bdr2.append(y_bdr2[j])

        A1_train_bdr2.append(A1[i])
        A2_train_bdr2.append(A2[i])
        B1_train_bdr2.append(B1[i])
        B2_train_bdr2.append(B2[i])
        C1_train_bdr2.append(C1[i])
        C2_train_bdr2.append(C2[i])

X_train_branch_bdr2=np.array(X_train_branch_bdr2)
X_train_trunck_bdr2=np.array(X_train_trunck_bdr2)


A1_train_bdr2=np.array(A1_train_bdr2)
A2_train_bdr2=np.array(A2_train_bdr2)
B1_train_bdr2=np.array(B1_train_bdr2)
B2_train_bdr2=np.array(B2_train_bdr2)
C1_train_bdr2=np.array(C1_train_bdr2)
C2_train_bdr2=np.array(C2_train_bdr2)

X_train_br=tf.convert_to_tensor(X_train_branch, dtype=tf.float32, dtype_hint=None, name=None)
X_train_tr=tf.convert_to_tensor(X_train_trunck, dtype=tf.float32, dtype_hint=None, name=None)
A1_train=tf.convert_to_tensor(A1_train, dtype=tf.float32, dtype_hint=None, name=None)
A2_train=tf.convert_to_tensor(A2_train, dtype=tf.float32, dtype_hint=None, name=None)
B1_train=tf.convert_to_tensor(B1_train, dtype=tf.float32, dtype_hint=None, name=None)
B2_train=tf.convert_to_tensor(B2_train, dtype=tf.float32, dtype_hint=None, name=None)
C1_train=tf.convert_to_tensor(C1_train, dtype=tf.float32, dtype_hint=None, name=None)
C2_train=tf.convert_to_tensor(C2_train, dtype=tf.float32, dtype_hint=None, name=None)
y_true=tf.convert_to_tensor(y_true, dtype=tf.float32, dtype_hint=None, name=None)

X_train_br_bdr=tf.convert_to_tensor(X_train_branch_bdr, dtype=tf.float32, dtype_hint=None, name=None)
X_train_tr_bdr=tf.convert_to_tensor(X_train_trunck_bdr, dtype=tf.float32, dtype_hint=None, name=None)
A1_train_bdr=tf.convert_to_tensor(A1_train_bdr, dtype=tf.float32, dtype_hint=None, name=None)
A2_train_bdr=tf.convert_to_tensor(A2_train_bdr, dtype=tf.float32, dtype_hint=None, name=None)
B1_train_bdr=tf.convert_to_tensor(B1_train_bdr, dtype=tf.float32, dtype_hint=None, name=None)
B2_train_bdr=tf.convert_to_tensor(B2_train_bdr, dtype=tf.float32, dtype_hint=None, name=None)
C1_train_bdr=tf.convert_to_tensor(C1_train_bdr, dtype=tf.float32, dtype_hint=None, name=None)
C2_train_bdr=tf.convert_to_tensor(C2_train_bdr, dtype=tf.float32, dtype_hint=None, name=None)

X_train_br_bdr2=tf.convert_to_tensor(X_train_branch_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
X_train_tr_bdr2=tf.convert_to_tensor(X_train_trunck_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
A1_train_bdr2=tf.convert_to_tensor(A1_train_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
A2_train_bdr2=tf.convert_to_tensor(A2_train_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
B1_train_bdr2=tf.convert_to_tensor(B1_train_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
B2_train_bdr2=tf.convert_to_tensor(B2_train_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
C1_train_bdr2=tf.convert_to_tensor(C1_train_bdr2, dtype=tf.float32, dtype_hint=None, name=None)
C2_train_bdr2=tf.convert_to_tensor(C2_train_bdr2, dtype=tf.float32, dtype_hint=None, name=None)

dataset = tf.data.Dataset.from_tensor_slices((X_train_br, X_train_tr, A1_train,A2_train,B1_train,B1_train,C1_train,C2_train,y_true))
dataset_bdr=tf.data.Dataset.from_tensor_slices((X_train_br_bdr, X_train_tr_bdr, A1_train_bdr,A2_train_bdr,B1_train_bdr,B2_train_bdr,C1_train_bdr,C2_train_bdr))
dataset_bdr2=tf.data.Dataset.from_tensor_slices((X_train_br_bdr2, X_train_tr_bdr2, A1_train_bdr2,A2_train_bdr2,B1_train_bdr2,B2_train_bdr2,C1_train_bdr2,C2_train_bdr2))

batch_size = 25000  # Adjust this based on needs
batch_size_bdr = 4000
batch_size_bdr2 = 4000

dataset = dataset.batch(batch_size)
dataset_bdr = dataset_bdr.batch(batch_size_bdr)
dataset_bdr2 = dataset_bdr2.batch(batch_size_bdr2)


# Define the optimizer
optimizer = tf.keras.optimizers.Adam()
tf.keras.backend.set_floatx('float32')

################### ~model for deepOnet~ #########################################################

#no of sensor points
m=n_coeffs
branch_input = Input(shape=(m,), name='vector_input')
trunck_input = Input(shape=(2,), name='scalar_input')

#branch network
branch_net = Dense(128, activation='tanh')(branch_input)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(128, activation='tanh')(branch_net)
branch_net = Dense(m, activation='tanh')(branch_net)

# Trunck network
trunck_net = Dense(128, activation='tanh')(trunck_input)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(128, activation='tanh')(trunck_net)
trunck_net = Dense(m, activation='tanh')(trunck_net)
#bias = tf.Variable(0., shape=(), trainable=True)

dot_product = Lambda(lambda x: tf.reduce_sum(x[0] * x[1], axis=1, keepdims=True))([branch_net, trunck_net])
model = tf.keras.Model(inputs=[branch_input, trunck_input], outputs=dot_product)

############################# Loss Functions ##################################################

def PINN_loss(X_br,X_tr,A1_tr,A2_tr,B1_tr,B2_tr,C1_tr,C2_tr):
    with tf.GradientTape(persistent=True) as tape:
            x,t=tf.unstack(X_tr,axis=1)
            tape.watch(x)
            tape.watch(t)

            s = model([X_br, tf.stack((x,t),axis=1)], training=True)
            dsdx=tape.gradient(s,x)
            d2sdx2=tape.gradient(dsdx,x)

            dsdt=tape.gradient(s,t)
            u=fun(A1_tr,A2_tr,B1_tr,B2_tr,C1_tr,C2_tr,x)

            loss = tf.reduce_mean(tf.square(dsdt-D_coeff*d2sdx2-K_coeff*tf.square(s)-u))

    del tape
    return loss

def data_loss(X_br,X_tr,y_tr):
    with tf.GradientTape(persistent=True) as tape:

            #x,t=tf.unstack(X_tr,axis=1)
            #tape.watch(x)
            #tape.watch(t)
            s = model([X_br, X_tr], training=True)
            loss = tf.reduce_mean(tf.square(s-y_tr))
    del tape
    return loss

def loss_bdr(X_br,X_tr,A1_tr,A2_tr,B1_tr,B2_tr,C1_tr,C2_tr):
    with tf.GradientTape(persistent=True) as tape:

            x,t=tf.unstack(X_tr,axis=1)
            tape.watch(x)
            tape.watch(t)

            s = model([X_br, tf.stack((x,t),axis=1)], training=True)
            dsdx=tape.gradient(s,x)
            d2sdx2=tape.gradient(dsdx,x)

            dsdt=tape.gradient(s,t)
            u=fun(A1_tr,A2_tr,B1_tr,B2_tr,C1_tr,C2_tr,x)

            loss2=tf.reduce_mean(tf.square(s))#initial loss
            loss = tf.reduce_mean(tf.square(dsdt-D_coeff*d2sdx2-K_coeff*tf.square(s)-u))#equation loss

    del tape
    return (loss+loss2)/2

def loss_bdr2(X_br,X_tr,C_tr):
    with tf.GradientTape(persistent=True) as tape:

            x,t=tf.unstack(X_tr,axis=1)
            xl=x+L
            tape.watch(x)
            tape.watch(t)
            tape.watch(xl)

            s = model([X_br, tf.stack((x,t),axis=1)], training=True)
            s1 = model([X_br, tf.stack((xl,t),axis=1)], training=True)

            dsdx=tape.gradient(s,x)
            d2sdx2=tape.gradient(dsdx,x)

            ds1dx=tape.gradient(s1,xl)
            d2s1dx2=tape.gradient(ds1dx,xl)

            dsdt=tape.gradient(s,t)
            ds1dt=tape.gradient(s1,t)
            u=fun(A1_tr,A2_tr,B1_tr,B2_tr,C1_tr,C2_tr,x)

            loss_bdr=tf.reduce_mean(tf.square(s-s1))
            loss_bdr_2=tf.reduce_mean(tf.square(dsdx-ds1dx))

            loss1 = tf.reduce_mean(tf.square(dsdt-D_coeff*d2sdx2-K_coeff*tf.square(s)-u))#equation loss at x=0
            loss2 = tf.reduce_mean(tf.square(ds1dt-D_coeff*d2s1dx2-K_coeff*tf.square(s1)-u))#equation loss at x=L

    del tape
    return (loss_bdr+loss_bdr_2)/4

#Ration of no of PINN loss points to data loss"
equations_to_data_ratio=20/1

# Define a learning rate schedule
initial_learning_rate = 1e-3
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate, decay_steps=100, decay_rate=0.9)

# Define the optimizer with the learning rate schedule
optimizer = tf.keras.optimizers.Adam(learning_rate=lr_schedule)

loss_total3=[]
epochs=[]
time3=[]
######################### TRAINING LOOP ######################################
start3=time.time()
for epoch in range(500):

    #randomly shuffling the dataset
    #dataset = dataset.shuffle(buffer_size=len(X_train_br))
    '.............................................................................'
    # PINN
    for X_br, X_tr,A1_tr,A2_tr,B1_tr,B2_tr,C1_tr,C2_tr,y_true in dataset:
        with tf.GradientTape() as tape:
            loss_value = PINN_loss(X_br,X_tr,A1_tr,A2_tr,B1_tr,B2_tr,C1_tr,C2_tr)
            grads = tape.gradient(loss_value, model.trainable_variables)
            optimizer.apply_gradients(zip(grads, model.trainable_variables))
        del tape
    '.............................................................................'
    # Data
#     loss_value_data=0

#     if(epoch%(equations_to_data_ratio)==0):
#         for X_br, X_tr, A,B,y_true in dataset:
#             with tf.GradientTape() as tape:

#                 loss_value_data = data_loss(X_br,X_tr,y_true)
#             grads = tape.gradient(loss_value_data, model.trainable_variables)
#             optimizer.apply_gradients(zip(grads, model.trainable_variables))

    '.............................................................................'
    # Initial
    for X_br, X_tr,A1_tr,A2_tr,B1_tr,B2_tr,C1_tr,C2_tr in dataset_bdr:
        with tf.GradientTape() as tape:

            loss_value_bdr = loss_bdr(X_br,X_tr,A1_tr,A2_tr,B1_tr,B2_tr,C1_tr,C2_tr)
        grads = tape.gradient(loss_value_bdr, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))
        del tape
    '.............................................................................'
   # Boundary

#     for X_br, X_tr, A,B in dataset_bdr2:
#         with tf.GradientTape() as tape:
#             loss_value_bdr2 = loss_bdr2(X_br,X_tr,A,B)
#         grads = tape.gradient(loss_value_bdr2, model.trainable_variables)
#         optimizer.apply_gradients(zip(grads, model.trainable_variables))


    '.............................................................................'

    loss_total_f=loss_value+loss_value_bdr#+loss_value_data#+loss_value_bdr2
    loss_total3.append(loss_total_f)
    epochs.append(epoch)

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, loss={loss_total_f:.6f}")
#     print(f"Epoch {epoch}, loss={loss_value:.6f}", end='\r')
    t=time.time()
    time3.append(t)
    ################################################################################

end3=time.time()
print((end3-start3)/100)

"""# Comparision between PI-Deeponet and SPI-Deeponet"""

# plt.xlabel('Time')
# plt.ylabel('Mean Squared Error')
# plt.loglog(np.array(time1)-start1, loss_total, label='PI-Deeponet')
# plt.loglog(np.array(time2)-start2, loss_total2, label='SPI-Deeponet')
# plt.loglog(np.array(time3)-start3, loss_total3, label='Taylor series-Deeponet')
# plt.legend()
# plt.show()

"""##Error plot"""

# plt.xlabel('epochs')
# plt.ylabel('Mean Squared Error')
# plt.loglog(epochs, loss_total, label='PI-Deeponet')
# plt.loglog(epochs, loss_total2, label='SPI-Deeponet')
# plt.loglog(epochs, loss_total3, label='Taylor series-Deeponet')
# plt.legend()
# plt.show()

# plt.xlabel('epochs')
# plt.ylabel('Mean Squared Error')
# plt.plot(epochs, np.array(time1)-start1, label='PI-Deeponet')
# plt.plot(epochs, np.array(time2)-start2, label='SPI-Deeponet')
# plt.plot(epochs, np.array(time3)-start3, label='Taylor series-Deeponet')
# plt.legend()
# plt.show()

"""##Testing on new functions"""

#prediction for a-new function, test new data preparation
A_new=np.random.rand()
B_new=np.random.rand()
X_test_branch=[]
X_test_trunck=[]

f_new=fn(A_new,B_new,x_sensor)
for i in range(1):
    for j in range(n_train):
        X_test_branch.append(f_new)
        X_test_trunck.append(y[j])

#testing data
X_test_branch=np.array(X_test_branch)
X_test_trunck=np.array(X_test_trunck)

#new unseen function pred
with tf.GradientTape(persistent=True) as tape:
    x, t = tf.unstack(X_test_trunck, axis=1)
    tape.watch(x)
    tape.watch(t)
    s=model([X_test_branch,x,t])
    pred=tf.reshape(s,(nx,nt))

    fig, axes = plt.subplots(1, 2, figsize=(16, 4))

    # First set of plots
    ax1 = axes[0]
    ax1.set_title('PI-DeepOnet Prediction')
    im1 = ax1.imshow(pred, cmap='jet', origin='lower')
    fig.colorbar(im1, orientation='vertical')

    # Second set of plots
    ax2 = axes[1]
    ax2.set_title('Numerical solution')
    x = np.linspace(0, 1, nx)
    t = np.linspace(0, 1, nt)
    u_inp_fun = fn(A_new, B_new, x)
    sol_fun = sol_reaction_diff(u_inp_fun, t, K_coeff, D_coeff)
    im2 = ax2.imshow(sol_fun, cmap='jet', origin='lower')
    fig.colorbar(im2, orientation='vertical')

    plt.show()

"""##Mean Squared error of the PI-DeepOnet solution for the new function"""

# np.mean((pred-sol_fun)**2)

"""##**R2 Scores of the prediction**"""

# r2=1-(np.sum((pred-sol_fun)**2)/(np.sum((sol_fun-np.mean(sol_fun))**2)))
# print(r2)

"""##Test on 1000 new functions"""

# r2_scores=[]
# for i in range(250):
#     A_new=np.random.rand()
#     B_new=np.random.rand()
#     X_test_branch=[]
#     X_test_trunck=[]

#     f_new=fn(A_new,B_new,x_sensor)
#     for k in range(1):
#         for j in range(n_train):
#             X_test_branch.append(f_new)
#             X_test_trunck.append(y[j])

#       #testing data
#     X_test_branch=np.array(X_test_branch)
#     X_test_trunck=np.array(X_test_trunck)

#       #new unseen function pred
#     s=model([X_test_branch, X_test_trunck])
#     pred=tf.reshape(s,(nx,nt))

#   #numerical sol for the test function
#     x=np.linspace(0,1,nx)
#     t=np.linspace(0,1,nt)
#     u_inp_fun=fn(A_new,B_new,x)
#     sol_fun =  sol_reaction_diff(u_inp_fun,t,K_coeff,D_coeff)
#     r2=1-(np.sum((pred-sol_fun)**2)/(np.sum((sol_fun-np.mean(sol_fun))**2)))
#     r2_scores.append(r2)

#     if(i%50==0):
#         print(i/100)
#         fig, axes = plt.subplots(1, 3, figsize=(16, 4))

#         # First set of plots
#         ax1 = axes[0]
#         ax1.set_title('PI-DeepOnet Prediction')
#         im1 = ax1.imshow(pred, cmap='jet', origin='lower')
#         fig.colorbar(im1, orientation='vertical')

#         # Second set of plots
#         ax2 = axes[1]
#         ax2.set_title('Numerical solution')
#         x = np.linspace(0, 1, nx)
#         t = np.linspace(0, 1, nt)
#         u_inp_fun = fn(A_new, B_new, x)
#         sol_fun = sol_reaction_diff(u_inp_fun, t, K_coeff, D_coeff)
#         im2 = ax2.imshow(sol_fun, cmap='jet', origin='lower')
#         fig.colorbar(im2, orientation='vertical')

#         ax3 = axes[2]
#         ax3.set_title('Error')
#         im3 = ax3.imshow((100*(sol_fun-pred)**2)/(sol_fun), cmap='jet', origin='lower')
#         fig.colorbar(im3, orientation='vertical')
#         print(np.mean(100*(sol_fun-pred)**2/np.max(sol_fun),axis=None),"% error")
#         plt.show()

# plt.xlabel('nth function')
# plt.ylabel('R2 Scores')
# plt.scatter(np.arange(len(r2_scores)),r2_scores)

# #observation-mean r2 score increases with #of functions
# avg_r2=np.sum(np.array(r2_scores))/len(r2_scores)
# print(avg_r2)

# def new_fn(A,B,x):
#     return A*x+B*x**2+A+B**2

# #prediction for a-new function, test new data preparation
# A_new=np.random.rand()
# B_new=np.random.rand()
# X_test_branch=[]
# X_test_trunck=[]

# f_new=fn(A_new,B_new,x_sensor)
# for i in range(1):
#     for j in range(n_train):
#         X_test_branch.append(f_new)
#         X_test_trunck.append(y[j])

# #testing data
# X_test_branch=np.array(X_test_branch)
# X_test_trunck=np.array(X_test_trunck)

# #new unseen function pred
# s=model([X_test_branch, X_test_trunck])
# pred=tf.reshape(s,(nx,nt))

# fig = plt.figure(figsize=(16,4))
# ax1 = fig.add_subplot(121)
# ax1.set_title('PI-DeepOnet Prediction')
# im1 = ax1.imshow(pred,cmap='jet',origin='lower')
# fig.colorbar(im1, orientation='vertical')

# #numerical sol for the test function
# x=np.linspace(0,1,nx)
# t=np.linspace(0,1,nt)
# u_inp_fun=fn(A_new,B_new,x)
# sol_fun =  sol_reaction_diff(u_inp_fun,t,K_coeff,D_coeff)

# #plot the results
# fig2 = plt.figure(figsize=(16,4))
# ax2 = fig2.add_subplot(121)
# ax2.set_title('Numerical solution')
# im2 = ax2.imshow(sol_fun,cmap='jet',origin='lower')
# fig2.colorbar(im2, orientation='vertical')
# plt.show()

# r2=1-(np.sum((pred-sol_fun)**2)/(np.sum((sol_fun-np.mean(sol_fun))**2)))
# print(r2)

#add different types of fnx in training
#PINN comparision

# def train(PINN_to_data_ratio,epochs_total):

#     model = tf.keras.Model(inputs=[branch_input, trunck_input], outputs=dot_product)
#     #Ration of no of PINN loss points to data loss"
#     equations_to_data_ratio=PINN_to_data_ratio

#     # Define a learning rate schedule
#     initial_learning_rate = 1e-3
#     lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
#         initial_learning_rate, decay_steps=100, decay_rate=0.9)

#     # Define the optimizer with the learning rate schedule
#     optimizer = tf.keras.optimizers.Adam(learning_rate=lr_schedule)

#     loss_total=[]
#     epochs=[]

#     ######################### TRAINING LOOP ######################################
#     for epoch in range(epochs_total):
#         #randomly shuffling the dataset
#         #dataset = dataset.shuffle(buffer_size=len(X_train_br))
#         '.............................................................................'
#         # PINN
#         for X_br, X_tr, A,B,y_true in dataset:
#             with tf.GradientTape() as tape:
#                 loss_value = PINN_loss(X_br,X_tr,A,B)
#             grads = tape.gradient(loss_value, model.trainable_variables)
#             optimizer.apply_gradients(zip(grads, model.trainable_variables))
#         '.............................................................................'
#         # Data
#         loss_value_data=0
#         if(epoch%(equations_to_data_ratio)==0):
#             for X_br, X_tr, A,B,y_true in dataset:
#                 with tf.GradientTape() as tape:

#                     loss_value_data = data_loss(X_br,X_tr,y_true)
#                 grads = tape.gradient(loss_value_data, model.trainable_variables)
#                 optimizer.apply_gradients(zip(grads, model.trainable_variables))

#         '.............................................................................'
#         # Initial
#         for X_br, X_tr, A,B in dataset_bdr:
#             with tf.GradientTape() as tape:

#                 loss_value_bdr = loss_bdr(X_br,X_tr,A,B)
#             grads = tape.gradient(loss_value_bdr, model.trainable_variables)
#             optimizer.apply_gradients(zip(grads, model.trainable_variables))
#         '.............................................................................'
#        # Boundary
#         '''
#         for X_br, X_tr, A,B in dataset_bdr2:
#             with tf.GradientTape() as tape:
#                 loss_value_bdr2 = loss_bdr2(X_br,X_tr,A,B)
#             grads = tape.gradient(loss_value_bdr2, model.trainable_variables)
#             optimizer.apply_gradients(zip(grads, model.trainable_variables))

#         '''
#         '.............................................................................'

#         loss_total_f=loss_value+loss_value_bdr+loss_value_data#+loss_value_bdr2
#         loss_total.append(loss_total_f)
#         epochs.append(epoch)

#         if epoch % 20 == 0:
#             print(f"Epoch {epoch}, loss={loss_total_f:.6f}")
#         #print(f"Epoch {epoch}, loss={loss_value:.6f}", end='\r')
#     ##################################################################################


#     r2_scores=[]
#     for i in range(250):
#         A_new=np.random.rand()
#         B_new=np.random.rand()
#         X_test_branch=[]
#         X_test_trunck=[]

#         f_new=fn(A_new,B_new,x_sensor)
#         for k in range(1):
#             for j in range(n_train):
#                 X_test_branch.append(f_new)
#                 X_test_trunck.append(y[j])

#           #testing data
#         X_test_branch=np.array(X_test_branch)
#         X_test_trunck=np.array(X_test_trunck)

#           #new unseen function pred
#         s=model([X_test_branch, X_test_trunck])
#         pred=tf.reshape(s,(nx,nt))

#       #numerical sol for the test function
#         x=np.linspace(0,1,nx)
#         t=np.linspace(0,1,nt)
#         u_inp_fun=fn(A_new,B_new,x)
#         sol_fun =  sol_reaction_diff(u_inp_fun,t,K_coeff,D_coeff)
#         r2=1-(np.sum((pred-sol_fun)**2)/(np.sum((sol_fun-np.mean(sol_fun))**2)))
#         r2_scores.append(r2)

#     avg_r2=np.sum(np.array(r2_scores))/len(r2_scores)
#     print("Average R2 for 250 test functions =",avg_r2)

#     return avg_r2,loss_total,epochs

# ratios=[10,20,30,40]
# R2=[]
# for x in ratios:
#     r2,loss,epochs=train(x,300)
#     R2.append(r2)
#     plt.plot(epochs,loss)

# plt.plot(ratios,R2)

#test for the same functions